package it.ccse.bandiEsperti.business.model;

// Generated 6-lug-2015 15.46.34 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssCampiOperatoriId generated by hbm2java
 */
@Embeddable
public class AssCampiOperatoriId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idCampoRicerca;
	private int idOperatoreRicerca;

	public AssCampiOperatoriId() {
	}

	public AssCampiOperatoriId(int idCampoRicerca, int idOperatoreRicerca) {
		this.idCampoRicerca = idCampoRicerca;
		this.idOperatoreRicerca = idOperatoreRicerca;
	}

	@Column(name = "id_campo_ricerca", nullable = false)
	public int getIdCampoRicerca() {
		return this.idCampoRicerca;
	}

	public void setIdCampoRicerca(int idCampoRicerca) {
		this.idCampoRicerca = idCampoRicerca;
	}

	@Column(name = "id_operatore_ricerca", nullable = false)
	public int getIdOperatoreRicerca() {
		return this.idOperatoreRicerca;
	}

	public void setIdOperatoreRicerca(int idOperatoreRicerca) {
		this.idOperatoreRicerca = idOperatoreRicerca;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssCampiOperatoriId))
			return false;
		AssCampiOperatoriId castOther = (AssCampiOperatoriId) other;

		return (this.getIdCampoRicerca() == castOther.getIdCampoRicerca())
				&& (this.getIdOperatoreRicerca() == castOther
						.getIdOperatoreRicerca());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCampoRicerca();
		result = 37 * result + this.getIdOperatoreRicerca();
		return result;
	}

}
