package it.ccse.bandiEsperti.business.model;

// Generated 13-lug-2015 15.43.52 by Hibernate Tools 3.4.0.CR1

import java.util.Iterator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Associazioni generated by hbm2java
 */
@Entity
@Table(name = "associazioni")
public class Associazioni implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Delibera delibera;
	private Esperto esperto;
	private Tema tema;


	public Associazioni() {
	}

	public Associazioni(int id, Delibera delibera, Esperto esperto, Tema tema) {
		this.id = id;
		this.delibera = delibera;
		this.esperto = esperto;
		this.tema = tema;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_delibera", nullable = false)
	public Delibera getDelibera() {
		return this.delibera;
	}

	public void setDelibera(Delibera delibera) {
		this.delibera = delibera;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_esperto", nullable = false)
	public Esperto getEsperto() {
		return this.esperto;
	}

	public void setEsperto(Esperto esperto) {
		this.esperto = esperto;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_tema", nullable = false)
	public Tema getTema() {
		return this.tema;
	}

	public void setTema(Tema tema) {
		this.tema = tema;
	}
	
	@Transient
	public String getTemi() {
		StringBuffer sb = new StringBuffer();
		
		Iterator<Associazioni> iter = this.getDelibera().getAssociazionis().iterator();
		while(iter.hasNext()){
			Associazioni associazione = (Associazioni) iter.next();
			if(this.getEsperto().getId() == associazione.getEsperto().getId()){
				sb.append(associazione.getTema().getNome());
				sb.append(" , ");
			}
		}
		
		return sb.toString().substring(0, sb.toString().length()-1);
		
	}
	
	
	@Transient
	public String getCodiceDelibera() {
		return this.delibera.getCodiceDelibera();
	}
	
	@Transient
	public String getDescrizioneDelibera() {
		return this.delibera.getDescrizioneDelibera();
	}
	
	@Transient
	public String getNome() {
		return this.esperto.getNome();
	}
	
	@Transient
	public String getCognome() {
		return this.esperto.getCognome();
	}
	
	
	
}
