package it.ccse.bandiEsperti.business.model;

// Generated 9-giu-2015 15.31.52 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Atenei generated by hbm2java
 */
@Entity
@Table(name = "atenei")
public class Atenei implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Citta citta;
	private String denominazione;
	private Set<Istruzione> istruziones = new HashSet<Istruzione>(0);

	public Atenei() {
	}

	public Atenei(Citta citta) {
		this.citta = citta;
	}

	public Atenei(Citta citta, String denominazione, Set<Istruzione> istruziones) {
		this.citta = citta;
		this.denominazione = denominazione;
		this.istruziones = istruziones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "citta_id", nullable = false)
	public Citta getCitta() {
		return this.citta;
	}

	public void setCitta(Citta citta) {
		this.citta = citta;
	}

	@Column(name = "denominazione", length = 100)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atenei")
	public Set<Istruzione> getIstruziones() {
		return this.istruziones;
	}

	public void setIstruziones(Set<Istruzione> istruziones) {
		this.istruziones = istruziones;
	}

}
