package it.ccse.bandiEsperti.business.model;
// Generated 5-giu-2015 13.46.42 by Hibernate Tools 3.4.0.CR1


import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Citta generated by hbm2java
 */
@Entity
@Table(name = "citta")
public class Citta implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Provincie provincie;
	private String codiceRegione;
	private String codiceCittaMetropolitana;
	private String comuneCapoluogo;
	private String denominazione;
	private Set<Esperto> espertis = new HashSet<Esperto>();
	private Set<Atenei> ateneis = new HashSet<Atenei>();

	public Citta() {
	}

	public Citta(Provincie provincie, String codiceRegione,
			String comuneCapoluogo, String denominazione) {
		this.provincie = provincie;
		this.codiceRegione = codiceRegione;
		this.comuneCapoluogo = comuneCapoluogo;
		this.denominazione = denominazione;
	}

	public Citta(Provincie provincie, String codiceRegione,
			String codiceCittaMetropolitana, String comuneCapoluogo,
			String denominazione, Set<Esperto> espertis, Set<Atenei> ateneis) {
		this.provincie = provincie;
		this.codiceRegione = codiceRegione;
		this.codiceCittaMetropolitana = codiceCittaMetropolitana;
		this.comuneCapoluogo = comuneCapoluogo;
		this.denominazione = denominazione;
		this.espertis = espertis;
		this.ateneis = ateneis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "codice_provincia", nullable = false, referencedColumnName="codice_provincia")
	public Provincie getProvincie() {
		return this.provincie;
	}

	public void setProvincie(Provincie provincie) {
		this.provincie = provincie;
	}

	@Column(name = "codice_regione", nullable = false, length = 2)
	public String getCodiceRegione() {
		return this.codiceRegione;
	}

	public void setCodiceRegione(String codiceRegione) {
		this.codiceRegione = codiceRegione;
	}

	@Column(name = "codice_citta_metropolitana", length = 3)
	public String getCodiceCittaMetropolitana() {
		return this.codiceCittaMetropolitana;
	}

	public void setCodiceCittaMetropolitana(String codiceCittaMetropolitana) {
		this.codiceCittaMetropolitana = codiceCittaMetropolitana;
	}

	@Column(name = "comune_capoluogo", nullable = false, length = 1)
	public String getComuneCapoluogo() {
		return this.comuneCapoluogo;
	}

	public void setComuneCapoluogo(String comuneCapoluogo) {
		this.comuneCapoluogo = comuneCapoluogo;
	}

	@Column(name = "denominazione", nullable = false, length = 45)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "citta")
	public Set<Esperto> getEspertis() {
		return this.espertis;
	}

	public void setEspertis(Set<Esperto> espertis) {
		this.espertis = espertis;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "citta")
	public Set<Atenei> getAteneis() {
		return this.ateneis;
	}

	public void setAteneis(Set<Atenei> ateneis) {
		this.ateneis = ateneis;
	}

}
