package it.ccse.bandiEsperti.business.model;

// Generated 15-giu-2015 10.27.23 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DatoreDiLavoro generated by hbm2java
 */
@Entity
@Table(name = "datore_di_lavoro")
public class DatoreDiLavoro implements IRicerca {

	
	private static final long serialVersionUID = -2784870528050250923L;
	private Integer id;
	private String denominazione;


	public DatoreDiLavoro() {
	}

	public DatoreDiLavoro(String denominazione) {
		this.denominazione = denominazione;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	

	@Column(name = "denominazione", nullable = false, length = 450)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}


}
