package it.ccse.bandiEsperti.business.model;

// Generated 18-giu-2015 10.20.12 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Delibera generated by hbm2java
 */
@Entity
@Table(name = "delibera")
public class Delibera implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8902183420653652774L;
	private int id;
	private String codiceDelibera;
	private String descrizioneDelibera;
	private Set<Associazioni> associazionis = new HashSet<Associazioni>(0);
	private Set<PrecedenteIncarico> precedenteIncaricos = new HashSet<PrecedenteIncarico>(
			0);

	public Delibera() {
	}

	public Delibera(int id, String codiceDelibera,
			String descrizioneDelibera) {
		this.id = id;
		this.codiceDelibera = codiceDelibera;
		this.descrizioneDelibera = descrizioneDelibera;
	}

	public Delibera(int id, String codiceDelibera,
			String descrizioneDelibera,
			Set<PrecedenteIncarico> precedenteIncaricos) {
		this.id = id;
		this.codiceDelibera = codiceDelibera;
		this.descrizioneDelibera = descrizioneDelibera;
		this.precedenteIncaricos = precedenteIncaricos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "codiceDelibera", nullable = false, length = 100)
	public String getCodiceDelibera() {
		return this.codiceDelibera;
	}

	public void setCodiceDelibera(String codiceDelibera) {
		this.codiceDelibera = codiceDelibera;
	}

	@Column(name = "descrizioneDelibera", nullable = false, length = 500)
	public String getDescrizioneDelibera() {
		return this.descrizioneDelibera;
	}

	public void setDescrizioneDelibera(String descrizioneDelibera) {
		this.descrizioneDelibera = descrizioneDelibera;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "delibera")
	public Set<PrecedenteIncarico> getPrecedenteIncaricos() {
		return this.precedenteIncaricos;
	}

	public void setPrecedenteIncaricos(
			Set<PrecedenteIncarico> precedenteIncaricos) {
		this.precedenteIncaricos = precedenteIncaricos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "delibera")
	public Set<Associazioni> getAssociazionis() {
		return this.associazionis;
	}

	public void setAssociazionis(Set<Associazioni> associazionis) {
		this.associazionis = associazionis;
	}

}
