package it.ccse.bandiEsperti.business.model;

// Generated 6-lug-2015 16.18.03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OperatoriRicerca generated by hbm2java
 */
@Entity
@Table(name = "operatori_ricerca")
public class OperatoriRicerca implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String etichetta;
	private String nome;
	private Set<AssCampiOperatori> assCampiOperatoris = new HashSet<AssCampiOperatori>(
			0);

	public OperatoriRicerca() {
	}

	public OperatoriRicerca(String etichetta, String nome) {
		this.etichetta = etichetta;
		this.nome = nome;
	}

	public OperatoriRicerca(String etichetta, String nome,
			Set<AssCampiOperatori> assCampiOperatoris) {
		this.etichetta = etichetta;
		this.nome = nome;
		this.assCampiOperatoris = assCampiOperatoris;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "etichetta", nullable = false, length = 45)
	public String getEtichetta() {
		return this.etichetta;
	}

	public void setEtichetta(String etichetta) {
		this.etichetta = etichetta;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operatoriRicerca")
	public Set<AssCampiOperatori> getAssCampiOperatoris() {
		return this.assCampiOperatoris;
	}

	public void setAssCampiOperatoris(Set<AssCampiOperatori> assCampiOperatoris) {
		this.assCampiOperatoris = assCampiOperatoris;
	}

}
