package it.ccse.bandiEsperti.business.model;

// Generated 5-giu-2015 13.46.42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Paesi generated by hbm2java
 */
@Entity
@Table(name = "paesi", uniqueConstraints = @UniqueConstraint(columnNames = "codice_paese"))
public class Paesi implements java.io.Serializable {

	
	private static final long serialVersionUID = -6334511942470450366L;
	private Integer id;
	private String codicePaese;
	private String denominazione;
	private Set<Esperto> espertis = new HashSet<Esperto>();
	private Set<Regioni> regionis = new HashSet<Regioni>();

	public Paesi() {
	}

	public Paesi(String codicePaese, String denominazione) {
		this.codicePaese = codicePaese;
		this.denominazione = denominazione;
	}

	public Paesi(String codicePaese, String denominazione,
			Set<Esperto> espertis, Set<Regioni> regionis) {
		this.codicePaese = codicePaese;
		this.denominazione = denominazione;
		this.espertis = espertis;
		this.regionis = regionis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "codice_paese", unique = true, nullable = false, length = 3)
	public String getCodicePaese() {
		return this.codicePaese;
	}

	public void setCodicePaese(String codicePaese) {
		this.codicePaese = codicePaese;
	}

	@Column(name = "denominazione", nullable = false, length = 45)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paesi")
	public Set<Esperto> getEspertis() {
		return this.espertis;
	}

	public void setEspertis(Set<Esperto> espertis) {
		this.espertis = espertis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paesi")
	public Set<Regioni> getRegionis() {
		return this.regionis;
	}

	public void setRegionis(Set<Regioni> regionis) {
		this.regionis = regionis;
	}

}
