package it.ccse.bandiEsperti.business.model;

// Generated 15-giu-2015 10.27.23 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Professione generated by hbm2java
 */
@Entity
@Table(name = "professione")
public class Professione implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String denominazione;
	private Set<EsperienzaLavorativa> esperienzeLavoratives = new HashSet<EsperienzaLavorativa>(
			0);

	public Professione() {
	}

	public Professione(String denominazione) {
		this.denominazione = denominazione;
	}

	public Professione(String professione,
			Set<EsperienzaLavorativa> esperienzeLavoratives) {
		this.esperienzeLavoratives = esperienzeLavoratives;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "denominazione", nullable = false, length = 450)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professione")
	public Set<EsperienzaLavorativa> getEsperienzeLavoratives() {
		return this.esperienzeLavoratives;
	}

	public void setEsperienzeLavoratives(
			Set<EsperienzaLavorativa> esperienzeLavoratives) {
		this.esperienzeLavoratives = esperienzeLavoratives;
	}

}
