package it.ccse.bandiEsperti.business.model;

// Generated 5-giu-2015 13.26.50 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RegioniId generated by hbm2java
 */
@Embeddable
public class RegioniId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String codiceRegione;

	public RegioniId() {
	}

	public RegioniId(int id, String codiceRegione) {
		this.id = id;
		this.codiceRegione = codiceRegione;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "codice_regione", unique = true, nullable = false, length = 2)
	public String getCodiceRegione() {
		return this.codiceRegione;
	}

	public void setCodiceRegione(String codiceRegione) {
		this.codiceRegione = codiceRegione;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RegioniId))
			return false;
		RegioniId castOther = (RegioniId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCodiceRegione() == castOther.getCodiceRegione()) || (this
						.getCodiceRegione() != null
						&& castOther.getCodiceRegione() != null && this
						.getCodiceRegione()
						.equals(castOther.getCodiceRegione())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37
				* result
				+ (getCodiceRegione() == null ? 0 : this.getCodiceRegione()
						.hashCode());
		return result;
	}

}
