package it.ccse.bandiEsperti.business.model;
// Generated 5-giu-2015 13.46.42 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Regioni generated by hbm2java
 */
@Entity
@Table(name = "regioni", uniqueConstraints = @UniqueConstraint(columnNames = "codice_regione"))
public class Regioni implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Paesi paesi;
	private String codiceRegione;
	private String denominazione;
	private Set<Provincie> provincies = new HashSet<Provincie>();
	private Set<Esperto> espertis = new HashSet<Esperto>();

	public Regioni() {
	}

	public Regioni(Paesi paesi, String codiceRegione, String denominazione) {
		this.paesi = paesi;
		this.codiceRegione = codiceRegione;
		this.denominazione = denominazione;
	}

	public Regioni(Paesi paesi, String codiceRegione, String denominazione,
			Set<Provincie> provincies, Set<Esperto> espertis) {
		this.paesi = paesi;
		this.codiceRegione = codiceRegione;
		this.denominazione = denominazione;
		this.provincies = provincies;
		this.espertis = espertis;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codice_paese", nullable = false, referencedColumnName="codice_paese")
	public Paesi getPaesi() {
		return this.paesi;
	}

	public void setPaesi(Paesi paesi) {
		this.paesi = paesi;
	}

	@Column(name = "codice_regione", unique = true, nullable = false, length = 2)
	public String getCodiceRegione() {
		return this.codiceRegione;
	}

	public void setCodiceRegione(String codiceRegione) {
		this.codiceRegione = codiceRegione;
	}

	@Column(name = "denominazione", nullable = false, length = 45)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regioni")
	public Set<Provincie> getProvincies() {
		return this.provincies;
	}

	public void setProvincies(Set<Provincie> provincies) {
		this.provincies = provincies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regioni")
	public Set<Esperto> getEspertis() {
		return this.espertis;
	}

	public void setEspertis(Set<Esperto> espertis) {
		this.espertis = espertis;
	}

}
