package it.ccse.bandiEsperti.business.model;

// Generated 9-giu-2015 12.47.06 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoLaurea generated by hbm2java
 */
@Entity
@Table(name = "tipo_laurea")
public class TipoLaurea implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String denominazione;
	private Set<Istruzione> istruziones = new HashSet<Istruzione>();
	private Set<TitoloLaurea> titoloLaureas = new HashSet<TitoloLaurea>();

	public TipoLaurea() {
	}

	public TipoLaurea(int id, String denominazione) {
		this.id = id;
		this.denominazione = denominazione;
	}

	public TipoLaurea(int id, String denominazione, 
			Set<Istruzione> istruziones, Set<TitoloLaurea> titoloLaureas) {
		this.id = id;
		this.denominazione = denominazione;
	
		this.istruziones = istruziones;
		this.titoloLaureas = titoloLaureas;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "denominazione", nullable = false, length = 450)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoLaurea")
	public Set<Istruzione> getIstruziones() {
		return this.istruziones;
	}

	public void setIstruziones(Set<Istruzione> istruziones) {
		this.istruziones = istruziones;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "tipoLaurea")
	public Set<TitoloLaurea> getTitoloLaureas() {
		return this.titoloLaureas;
	}

	public void setTitoloLaureas(Set<TitoloLaurea> titoloLaureas) {
		this.titoloLaureas = titoloLaureas;
	}

}
