package it.ccse.bandiEsperti.business.model;
// Generated 9-giu-2015 12.47.06 by Hibernate Tools 3.4.0.CR1

import it.ccse.bandiEsperti.business.command.interfaces.IRicerca;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TitoloLaurea generated by hbm2java
 */
@Entity
@Table(name = "titolo_laurea")
public class TitoloLaurea implements IRicerca {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private TipoLaurea tipoLaurea;
	private String denominazione;
	private Set<Istruzione> istruziones = new HashSet<Istruzione>();

	public TitoloLaurea() {
	}



	public TitoloLaurea(TipoLaurea tipoLaurea, String denominazione,
			Set<Istruzione> istruziones) {
		this.tipoLaurea = tipoLaurea;
		this.denominazione = denominazione;
		this.istruziones = istruziones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tipo_laurea_id")
	public TipoLaurea getTipoLaurea() {
		return this.tipoLaurea;
	}

	public void setTipoLaurea(TipoLaurea tipoLaurea) {
		this.tipoLaurea = tipoLaurea;
	}

	@Column(name = "denominazione", nullable = false, length = 450)
	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titoloLaurea")
	public Set<Istruzione> getIstruziones() {
		return this.istruziones;
	}

	public void setIstruziones(Set<Istruzione> istruziones) {
		this.istruziones = istruziones;
	}

	

}
